baseURL = "https://tanyakemmpere.github.io/"
defaultContentLanguage = "en"
languageCode = "en"

title = "~tanya~"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
  # URL for the avatar on homepage
  avatarURL = "images/avatar.jpg"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-l"

  description = "Sky above, sand below & peace within"

  accentColor = "#fdc70c"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo", "LabVeilleTech"]

  # Footer text
  footer = "Blog pour le cours LabVeilleTech"

[[menu.main]]
    identifier = "à propos"
    pre = "<span data-feather='info'></span>"
    url = "/a-propos"
    weight = 1

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = "<span data-feather='book'></span>"

    # Weights are used to determine the ordering
    weight = 2

  [[menu.main]]
    identifier = "tags"
    pre = "<span data-feather='bookmark'></span>"
    url = "/tags/"
    weight = 3
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/TanyaKemmPere"
    weight = 4
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"