baseURL = "http://example.org/"
defaultContentLanguage = "en"
languageCode = "en"

title = "~tanya~"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = "<span data-feather='book'></span>"

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "blog"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    pre="<span data-feather='bookmark'></span>"
    name = "tags"
    url = "/tags/"
    weight = 2
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/TanyaKemmPere"
    weight = 3
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"
    name = "mon git"

[params]
    description = "Bienvenue visiteur! Sur ce magnifique blog, on y trouve des articles passionnants qui parlent de moi :)"
    